### ISSUE TITLE
`Fathom::Client` can't be found

### ISSUE THREAD

**Issue by joemasilotti** [afomera/fathom_api#4]
Well, this is weird. `Fathom` can be resolved but not `Fathom::Client`. Any idea what could be going on here?

```
➜  rails git:(open-startup) ✗ bundle exec rails c
Loading development environment (Rails 7.0.1)
[1] pry(main)> Fathom::Client
NameError: uninitialized constant Fathom::Client
from (pry):1:in `__pry__'
[2] pry(main)> Fathom
=> Fathom
```

Also, _amazing_ that you have a gem for this! I need to do a single fetch for one metric and this looks perfect. Thank you!

**Comment by joemasilotti** [comment]
Well, it might help if I include the right gem...

Note for future self: this gem is `fathom_api`, not `fathom`!

**Comment by afomera** [comment]
Ahh thanks @joemasilotti! Sorry I didn't see this until now!
