### ISSUE TITLE
How to add `params` to aggregations?

### ISSUE THREAD

**Issue by joemasilotti** [afomera/fathom_api#5]
The [Fathom API docs](https://usefathom.com/api#aggregation) note that you can scope an aggregation query by passing a JSON payload to `filters`. I can't seem to get that to work without the API throwing an error.

Am I formatting the payload incorrectly or is this not yet supported in the gem?

```ruby
client = Fathom::Client.new(api_key: Rails.application.credentials.fathom.api_key)
entity_id = Rails.application.config.fathom
client.aggregations.list(
  entity_id:,
  entity: "pageview",
  aggregates: "visits",
  filters: [
    {
      property: "pathname",
      operator: "is",
      value: "/developers"
    }
  ]
)
```

The response is `Fathom::Error: We were unable to perform the request due to server-side problems.` in, oddly enough, HTML content.

**Comment by afomera** [comment]
Alright so I've looked at this @joemasilotti 

Here's what I found out, fathom is expecting the filters to be sent as a JSON payload. So... we have a couple options

We can 
1. Call to_json on this ourselves before sending it through, as the gem is going to just pass-through the params for that endpoint

```ruby
require 'json' # You may not have to do this inside of rails, I can't fully remember.

client = Fathom::Client.new(api_key: Rails.application.credentials.fathom.api_key)
entity_id = Rails.application.config.fathom
client.aggregations.list(
  entity_id:,
  entity: "pageview",
  aggregates: "visits",
  filters: [
    {
      property: "pathname",
      operator: "is",
      value: "/developers"
    }
  ].to_json
)

```

2. Or... we can patch the aggregations resource to do this for us automatically.

I'm leaning towards option 2 myself, but it may be surprising for folks. thoughts?

for the record this is what the aggregations resource would likely end up looking like

```ruby
    def list(entity_id:, entity:, aggregates:, **params)
      filters = params.delete(:filters) || {}
      get_request("aggregations", params: params.merge(entity_id: entity_id, entity: entity, aggregates: aggregates, filters: filters.to_json))
    end
```

**Comment by joemasilotti** [comment]
I like option 2 as well since it means I don't need to know the intervals of the API to run this query. 

However, that is technically a breaking change right? Is there a way to check if the value was already converted to JSON first?

Or, communicating the breaking change clearly could work. The library isn't technically at 1.0 yet.

**Comment by joemasilotti** [comment]
Thinking on this a bit more, we could do the following. That would be both backwards compatible and get the benefits of option 2.

```ruby
def list(entity_id:, entity:, aggregates:, **params)
  filters = params.delete(:filters) || {}
  filters = filters.to_json if filters.is_a?(Hash)
  get_request("aggregations", params: params.merge(entity_id: entity_id, entity: entity, aggregates: aggregates, filters: filters))
end
```

**Comment by afomera** [comment]
That sounds good I think, do you want to make that in a PR @joemasilotti? 

I think we'll just need to `require 'json'` at the top of the aggregations resource 👍

**Comment by joemasilotti** [comment]
Sure thing!

**Comment by joemasilotti** [comment]
PR submitted! PR #6.
